15 front end form for user log in
KC-LCW-Jan-23-Classroom/liftoff-Spooky-Cats pull request #29
Opened 2023-10-15 21:28 UTC by lyremlou

with some back end updates for /register and /login

2023-10-16 17:28 UTC, jlacy93 approved these changes

2023-10-18 01:20 UTC, Meliora347 commented on feral-cat-tracker-UI/src/app/app.module.ts
> +    LoginComponent
Needs a "," following LoginComponent

2023-10-18 01:21 UTC, Meliora347 commented on feral-cat-tracker-UI/src/app/app.module.ts
> +    HttpClientModule
Needs a "," following HttpClientModule

2023-10-18 01:23 UTC, Meliora347 requested changes
Needs commas added in app.module.ts following LoginComponent and HttpClientModule. It currently won't run, but WILL run when I make these changes.

2023-10-18 01:38 UTC, lyremlou commented on feral-cat-tracker-UI/src/app/app.module.ts
> +    LoginComponent
Got it!

2023-10-18 02:13 UTC, Meliora347 approved these changes

2023-10-18 02:47 UTC, merged