Search refinements
KC-LCW-Jan-23-Classroom/liftoff-Spooky-Cats pull request #64
Opened 2023-11-06 18:01 UTC by lyremlou

Choose search query by radio button. 
Added "Color" radio button.
No selected button searches all fields.

2023-11-07 22:39 UTC, jlacy93 approved these changes
This is awesome!

2023-11-08 01:54 UTC, Meliora347 requested changes
All searches only search for microchip number. Seems to have a backend query problem. Branch in behind main, need to pull main and merge into this branch.

2023-11-08 02:37 UTC, lyremlou commented
This is the cat controller in the new file, so it should differentiate between queries

<img width="583" alt="Screenshot 2023-11-07 at 8 24 23 PM" src="https://github.com/KC-LCW-Jan-23-Classroom/liftoff-Spooky-Cats/assets/95884852/9c14fb3f-22ba-4d18-bdbf-2919f1e32a88">

2023-11-10 01:18 UTC, Meliora347 approved these changes

2023-11-10 01:19 UTC, merged